#!/bin/bash

source /home/`whoami`/.low-battery

VAR_SLEEP=$REGULAR_SLEEP
status=`upower -i $(upower -e | grep 'BAT') | grep -E 'state|percentage'`
while true; do
  if [ `echo $status | grep -o -E *discharging*` = discharging ] && [ `echo $status | grep -o -P [1-9]+` -le $CRITICAL ]; then
    ( speaker-test -t sine -f $FREQUENCY > /dev/null)& pid=$! ; sleep ${SECONDS}s ; kill -9 $pid
    VAR_SLEEP=$CRITICAL_SLEEP
  elif [ `echo $status | grep -o -E *discharging*` = discharging ] && [ `echo $status | grep -o -P [1-9]+` -le $LOW ]; then 
    ( speaker-test -t sine -f $FREQUENCY > /dev/null)& pid=$! ; sleep ${SECONDS}s ; kill -9 $pid
    VAR_SLEEP=$LOW_SLEEP
  else
    VAR_SLEEP=$REGULAR_SLEEP
  fi
  sleep $VAR_SLEEP;
done
